const data={
  courses:[
    {title:'JEE Main + Advanced',tag:'ENGINEERING',desc:'Structured preparation for Physics, Chemistry and Mathematics with rigorous problem solving and test practice.',image:'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1200&q=85'},
    {title:'NEET-UG',tag:'MEDICAL',desc:'Concept-first preparation across Biology, Physics and Chemistry with regular assessment and mentoring.',image:'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=1200&q=85'},
    {title:'Foundation',tag:'CLASSES 8–10',desc:'Build strong fundamentals in Science and Mathematics before the competitive-exam journey begins.',image:'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=85'},
    {title:'Boards + GUJCET',tag:'GSEB / CBSE',desc:'Integrated board preparation with competitive-exam readiness for students targeting Gujarat entrance pathways.',image:'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=85'},
    {title:'Olympiads & NTSE',tag:'FOUNDATION',desc:'Problem-solving focused academic enrichment for students aiming to strengthen reasoning and conceptual depth.',image:'https://images.unsplash.com/photo-1560785496-3c9d27877182?auto=format&fit=crop&w=1200&q=85'}
  ]
};
const nav=(active='Home')=>`<header class="nav"><a class="brand" href="/"><span class="brand-mark">P²</span><span><b>Preparation</b><small>POINT • VAPI</small></span></a><nav>${['Home','About','Courses','Faculty','Admission','Contact'].map(x=>`<a class="${active===x?'active':''}" href="${x==='Home'?'/':`/pages/${x.toLowerCase()}.html`}">${x}</a>`).join('')}</nav><a class="nav-cta" href="/pages/admission.html">Enquire Now <span>↗</span></a><button class="menu" aria-label="menu">☰</button></header>`;
const footer=()=>`<footer><div class="footer-grid"><div><a class="brand" href="/"><span class="brand-mark">P²</span><span><b>Preparation</b><small>POINT • VAPI</small></span></a><p>Where preparation becomes performance. Structured coaching for ambitious students in Vapi.</p></div><div><h4>Explore</h4><a href="/pages/about.html">About P²</a><a href="/pages/courses.html">Courses</a><a href="/pages/faculty.html">Faculty</a></div><div><h4>Admissions</h4><a href="/pages/admission.html">Apply / Enquire</a><a href="/pages/contact.html">Centers & Contact</a><a href="/pages/courses.html">Programs</a></div><div><h4>Vapi Centers</h4><p>Chala • I-Square, Vapi<br>Gunjan • Breeze View Complex, Vapi</p><a href="https://www.google.com/maps/search/?api=1&query=Preparation+Point+Vapi" target="_blank">Open in Maps ↗</a></div></div><div class="footer-bottom"><span>© 2026 Preparation Point (P²)</span><span>JEE • NEET • FOUNDATION • BOARDS</span></div></footer>`;
const home=()=>`${nav()}<main><section class="hero"><div class="hero-copy"><div class="eyebrow"><span></span> VAPI'S STUDENT-FIRST COACHING</div><h1>Turn your <em>potential</em><br>into performance.</h1><p>Focused preparation for JEE, NEET, Foundation, Boards, GUJCET and Olympiads — built around strong concepts, consistent practice and personal guidance.</p><div class="hero-actions"><a class="btn primary" href="/pages/admission.html">Explore Admissions <span>→</span></a><a class="text-link" href="/pages/courses.html">View courses <span>↗</span></a></div><div class="proof"><div><strong>25K+</strong><span>Students guided*</span></div><div><strong>2016</strong><span>Founded*</span></div><div><strong>2</strong><span>Vapi centers</span></div></div></div><div class="hero-visual"><div class="hero-image"></div><div class="floating-card top"><span class="dot"></span><div><b>Concept → Practice → Progress</b><small>A structured learning loop</small></div></div><div class="floating-card bottom"><strong>P²</strong><div><b>Personal attention</b><small>Mentoring that keeps you moving</small></div></div><div class="scribble">YOUR<br>MOVE <span>↗</span></div></div></section>
<section class="marquee"><div>JEE MAIN + ADVANCED <i>✦</i> NEET-UG <i>✦</i> FOUNDATION <i>✦</i> GUJCET <i>✦</i> BOARDS <i>✦</i> OLYMPIADS <i>✦</i></div></section>
<section class="section intro"><div class="section-label">01 / THE P² APPROACH</div><div class="split"><div><h2>More than classes.<br><span>A preparation system.</span></h2></div><div><p class="lead">Preparation Point describes its approach around experienced faculty, structured learning systems, academic support and student-centric mentoring. We’ve translated that philosophy into a digital experience designed for both students and parents.</p><a class="text-link" href="/pages/about.html">Discover our approach ↗</a></div></div></section>
<section class="section dark"><div class="section-label light">02 / PROGRAMS</div><div class="section-head"><div><h2>Choose your <span>path.</span></h2></div><a class="outline" href="/pages/courses.html">All courses ↗</a></div><div class="course-grid">${data.courses.slice(0,3).map((c,i)=>`<a class="course-card" href="/pages/courses.html#course-${i}"><div class="course-img" style="background-image:url('${c.image}')"></div><div class="course-body"><span>${c.tag}</span><h3>${c.title}</h3><p>${c.desc}</p><b>Explore program →</b></div></a>`).join('')}</div></section>
<section class="section stats"><div class="stats-copy"><div class="section-label">03 / WHY P²</div><h2>Preparation with<br><span>purpose.</span></h2><p>Public profiles describe P² as serving competitive and school-level preparation across JEE, NEET, NTSE, Olympiads, GUJCET and Boards, with locations in Vapi.</p></div><div class="stat-grid"><div><strong>25,000+</strong><span>students guided*</span></div><div><strong>360°</strong><span>academic support</span></div><div><strong>2</strong><span>Vapi centers</span></div><div><strong>1</strong><span>student-first goal</span></div></div></section>
<section class="section feature"><div class="feature-image"></div><div class="feature-copy"><div class="section-label">04 / BUILT FOR FOCUS</div><h2>A calmer way to prepare for a competitive world.</h2><p>Clear course discovery. Faculty visibility. Straightforward admissions. Quick contact. The website is designed to reduce friction at every decision point.</p><div class="checks"><span>✓ Structured programs</span><span>✓ Regular assessment mindset</span><span>✓ Personal mentoring</span><span>✓ Parent-friendly information</span></div><a class="btn darkbtn" href="/pages/contact.html">Talk to P² <span>→</span></a></div></section>
<section class="cta"><div><div class="eyebrow">READY WHEN YOU ARE</div><h2>Your next chapter<br>starts with a plan.</h2></div><a class="btn lightbtn" href="/pages/admission.html">Start an enquiry ↗</a></section></main>${footer()}`;
function inner(title,kicker,content,active){return `${nav(active)}<main><section class="page-hero"><div class="section-label">${kicker}</div><h1>${title}</h1><p>${content}</p></section>`}
function about(){return inner('Built around the student.','ABOUT P²','Preparation Point is an education institute headquartered in Vapi, Gujarat. Publicly available information says it has guided 25,000+ students and focuses on JEE, NEET, Foundation, NTSE, Olympiads, GUJCET and board preparation.','About')+`<section class="section about-layout"><div><h2>The goal is simple: make preparation <span>intentional.</span></h2></div><div><p>Our digital experience is built around the public positioning of P²: strong faculty, structured systems, academic support and student-centric guidance.</p><p>Rather than overwhelming students with information, the site prioritizes the decisions that matter: which course fits, who will teach it, how admission works, where the center is, and how to ask for guidance.</p></div></section><section class="section dark"><div class="section-label light">WHAT WE VALUE</div><div class="value-grid"><article><b>01</b><h3>Concepts first</h3><p>Build understanding before chasing speed.</p></article><article><b>02</b><h3>Practice with intent</h3><p>Use questions and tests to convert learning into performance.</p></article><article><b>03</b><h3>Guidance matters</h3><p>Keep students moving with mentoring and doubt support.</p></article><article><b>04</b><h3>Measure progress</h3><p>Make improvement visible through regular assessment.</p></article></div></section></main>${footer()}`}
function courses(){return inner('Find your preparation path.','COURSES','Explore the programs publicly associated with Preparation Point. Course duration, fees, batch sizes and current schedules should be confirmed directly with the institute.','Courses')+`<section class="section course-list">${data.courses.map((c,i)=>`<article id="course-${i}" class="large-course"><div class="large-course-img" style="background-image:url('${c.image}')"></div><div><span>${c.tag}</span><h2>${c.title}</h2><p>${c.desc}</p><ul><li>Structured curriculum</li><li>Practice & assessment</li><li>Academic guidance</li><li>Study support</li></ul><a class="btn primary" href="/pages/admission.html">Enquire about this course →</a></div></article>`).join('')}</section></main>${footer()}`}
function faculty(){return inner('Meet the people behind the preparation.','FACULTY','A polished faculty directory is included in the experience. Names, qualifications, subjects and photographs should be populated from the institute’s current official faculty roster before launch.','Faculty')+`<section class="section faculty-note"><div class="notice"><b>Content-ready faculty system</b><p>This version deliberately avoids inventing teacher names or credentials. Add verified faculty profiles here with subject, qualification, teaching experience and a short teaching philosophy.</p></div><div class="faculty-grid">${['Physics','Chemistry','Mathematics','Biology','Foundation','Academic Mentoring'].map((x,i)=>`<article><div class="avatar">${['PHY','CHE','MAT','BIO','FND','MEN'][i]}</div><span>${x.toUpperCase()}</span><h3>Faculty Profile</h3><p>Verified profile content can be added by the institute.</p></article>`).join('')}</div></section></main>${footer()}`}
function admission(){return inner('Start with the right conversation.','ADMISSIONS','Tell us what you are preparing for and the academic team can guide you toward the appropriate program.','Admission')+`<section class="section admission-layout"><div><div class="section-label">ADMISSION FLOW</div><h2>Simple for students.<br><span>Clear for parents.</span></h2><div class="steps"><div><b>01</b><p><strong>Share your goal</strong><br>Tell us your class, exam and target.</p></div><div><b>02</b><p><strong>Speak to a counselor</strong><br>Discuss course fit, schedule and center.</p></div><div><b>03</b><p><strong>Choose your program</strong><br>Complete the institute’s admission process.</p></div></div></div><form class="lead-form" onsubmit="event.preventDefault();this.innerHTML='<div class=success><span>✓</span><h3>Enquiry captured.</h3><p>This demo form is frontend-only. Connect it to the institute email/CRM before launch.</p></div>'"><label>Student name<input required placeholder="Your name"></label><label>Parent / Guardian phone<input required type="tel" placeholder="10-digit mobile"></label><label>Class<select><option>Class 8</option><option>Class 9</option><option>Class 10</option><option>Class 11</option><option>Class 12</option><option>12th Passed</option></select></label><label>Interested in<select><option>JEE Main + Advanced</option><option>NEET-UG</option><option>Foundation</option><option>Boards + GUJCET</option><option>Olympiads / NTSE</option></select></label><button class="btn primary" type="submit">Request a call →</button><small>By submitting, you agree to be contacted about the enquiry.</small></form></div></main>${footer()}`}
function contact(){return inner('Let’s talk preparation.','CONTACT','Two Vapi locations are publicly listed for Preparation Point. Confirm current hours and contact details with the institute before publishing the final site.','Contact')+`<section class="section contact-grid"><div><div class="contact-card"><span>CHALA CENTER</span><h3>I-Square, F-8<br>Chala, Vapi</h3><a href="https://www.google.com/maps/search/?api=1&query=Preparation+Point+Chala+Vapi" target="_blank">Get directions ↗</a></div><div class="contact-card"><span>GUNJAN CENTER</span><h3>Breeze View Complex<br>Gunjan, Vapi</h3><a href="https://www.google.com/maps/search/?api=1&query=Preparation+Point+Gunjan+Vapi" target="_blank">Get directions ↗</a></div></div><div class="contact-panel"><div class="section-label">QUICK ENQUIRY</div><h2>Have a question?<br><span>Start here.</span></h2><p>For current batches, fees, scholarships and faculty availability, contact the institute directly.</p><a class="btn primary" href="tel:+919586966979">Call Preparation Point →</a><a class="text-link" href="mailto:info@preparationpoint.in">info@preparationpoint.in ↗</a></div></section></main>${footer()}`}
const path=location.pathname;let html=path.includes('about')?about():path.includes('courses')?courses():path.includes('faculty')?faculty():path.includes('admission')?admission():path.includes('contact')?contact():home();document.querySelector('#app').innerHTML=html;
document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('.nav nav').classList.toggle('open'));
